### ISSUE TITLE
Thank you very much for your work, I have some questions about training

### ISSUE THREAD

**Issue by Ganbingkun** [Xianjun-Yang/FewDocAE#4]
When I perform ‘python train_cross_6w2d.py --model nnshot --pretrain_ckpt bert-base-uncased’
An error was found 
~~~
6-way-1-shot Few-Shot NER
model: nnshot
max_length: 1024
mode: inter
loading model and tokenizer...
pretrain_ckpt: bert-base-uncased
word_encoder complete
tokenizer complete
Use episode data!
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
use nnshot
model-save-path: checkpoint/nnshot-inter-6-1-seed0.pth.tar
Start training...
Use bert optim!
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Traceback (most recent call last):
  File "/content/drive/MyDrive/FewDocAE/train_cross_6w2d.py", line 195, in <module>
    main()
  File "/content/drive/MyDrive/FewDocAE/train_cross_6w2d.py", line 177, in main
    framework.train(model, prefix,
  File "/content/drive/MyDrive/FewDocAE/util/framework.py", line 404, in train
    logits, pred = model(support, query)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/FewDocAE/model/nnshot.py", line 47, in forward
    support_emb = self.word_encoder(support['word'], support['mask']) # [num_sent, number_of_tokens, 768]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/data_parallel.py", line 183, in forward
    return self.module(*inputs[0], **module_kwargs[0])
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/FewDocAE/util/word_encoder.py", line 22, in forward
    outputs = self.bert(words, attention_mask=masks, output_hidden_states=True)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/bert/modeling_bert.py", line 979, in forward
    buffered_token_type_ids_expanded = buffered_token_type_ids.expand(batch_size, seq_length)
RuntimeError: The expanded size of the tensor (1024) must match the existing size (512) at non-singleton dimension 1.  Target sizes: [3, 1024].  Tensor sizes: [1, 512]
~~~
This is the full terminal output information，Thanks！

**Comment by Xianjun-Yang** [comment]
The error tells that You set max_length: 1024 but bert-base only
accepts.512.
